name: fuodz
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_theme: ^2.2.0
  basic_utils: ^3.3.3
  blue_thermal_printer: ^1.1.4
  cached_network_image: ^3.0.0
  cool_alert: ^1.0.3
  country_picker: ^2.0.6
  cupertino_icons: ^1.0.0
  double_back_to_close: ^2.0.0
  dartx: ^0.7.1
  dio: ^4.0.0
  dio_http_cache_lts: ^0.4.0
  dot_navigation_bar: ^0.1.1
  dotted_border: ^2.0.0
  dotted_line: ^2.0.2
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.3
  fl_chart: ^0.35.0
  flag: ^3.1.0
  flutter_bluetooth_basic: ^0.1.5
  flutter_form_builder: ^6.0.1
  flutter_icons: ^1.0.0+1
  flutter_local_notifications: ^6.0.0
  flutter_onboard: ^1.0.3
  flutter_staggered_animations: ^0.1.2
  flutter_svg: ^0.19.3
  google_fonts: ^2.1.0
  google_nav_bar: ^5.0.3
  i18n_extension: ^4.0.0
  image_picker: ^0.8.1+4
  in_app_review: ^2.0.2
  inspection: ^0.0.12
  jiffy: ^3.0.1
  line_icons: ^0.2.0
  map_launcher: ^1.1.3+1
  number_display: ^3.0.0
  numeral: ^1.0.4
  package_info: ^2.0.2
  pin_code_fields: ^6.1.0
  pretty_dio_logger: ^1.1.1
  provider: ^5.0.0
  pull_to_refresh: ^1.6.4
  random_string: ^2.1.0
  rx_shared_preferences: ^2.1.0
  shared_preferences: ^2.0.6
  stacked: ^1.7.6
  url_launcher: ^6.0.9
  velocity_x: ^3.3.0

dependency_overrides:
  rxdart: ^0.27.1
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  args: ^2.0.0
  flutter_application_id: ^1.0.0
  equatable: ^1.0.0
  firebase_chat: ^0.0.4
  cloud_firestore: ^1.0.3
  json_annotation: ^4.0.1
  yaml: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_application_id: "^1.0.0"
  flutter_launcher_icons: "^0.9.0"
  flutter_native_splash: ^1.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
